const mongoose = require('mongoose');
const Organization = require('../models/shared/Organization');
const Feature = require('../models/shared/Feature');
const SuperAdmin = require('../models/shared/SuperAdmin');
const logger = require('../utils/logger');
const { initializeTenantModels } = require('../utils/tenantDatabase');
const { seedTenantData } = require('../utils/seedTenantData');

/**
 * @desc    Create new organization
 * @route   POST /api/admin/organizations
 * @access  Private/SuperAdmin
 */
exports.createOrganization = async (req, res) => {
  try {
    const {
      name,
      slug,
      email,
      phone,
      address,
      subscriptionPlan,
      enabledFeatures,
      adminUser,
      settings,
      limits,
      seedData = true, // Flag to seed initial data
      copyFromOrg, // Optional: ID of organization to copy data from
    } = req.body;

    // Check if organization with same email or slug exists
    const existingOrg = await Organization.findOne({
      $or: [{ email }, { slug }]
    });

    if (existingOrg) {
      return res.status(400).json({
        success: false,
        message: 'Organization with this email or slug already exists',
      });
    }

    // Create organization (database name will be auto-generated by pre-save hook)
    const organization = await Organization.create({
      name,
      slug,
      email,
      phone,
      address,
      subscriptionPlan: subscriptionPlan || 'TRIAL',
      subscriptionStatus: 'ACTIVE',
      subscriptionStartDate: Date.now(),
      subscriptionEndDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // 30 days trial
      enabledFeatures: enabledFeatures || [],
      adminUser: {
        firstName: adminUser.firstName,
        lastName: adminUser.lastName,
        email: adminUser.email,
        phone: adminUser.phone,
        password: adminUser.password,
        isActive: true,
      },
      settings: settings || {},
      limits: limits || {},
      isActive: true,
      isVerified: true,
      verifiedAt: Date.now(),
      createdBy: req.user?._id, // Optional - handle cases where req.user might not exist
    });

    const dbName = organization.database.name;
    logger.info(`✓ Organization created: ${organization.name} (ID: ${organization._id})`);
    logger.info(`  Database name: ${dbName}`);
    logger.info(`  Created by: ${req.user.email}`);

    // Initialize tenant database and models
    let dbInitialized = false;
    let seedingResult = null;

    try {
      logger.info(`Initializing tenant database models for: ${dbName}`);
      await initializeTenantModels(dbName, organization._id);
      dbInitialized = true;
      logger.info(`✓ Tenant database models initialized`);

      // Seed initial data if requested
      if (seedData) {
        const seedOptions = {};

        // If copyFromOrg is provided, copy data from that organization
        if (copyFromOrg) {
          seedOptions.copyData = true;
          seedOptions.templateOrgId = copyFromOrg;
          logger.info(`Copying data from organization: ${copyFromOrg}`);
        } else {
          logger.info(`Seeding default data for new organization`);
        }

        seedingResult = await seedTenantData(dbName, organization._id, seedOptions);
        logger.info(`✓ Initial data seeded successfully for ${organization.name}`);
        logger.info(`  Data created: ${JSON.stringify(seedingResult.data)}`);
      } else {
        logger.warn(`⚠ Seeding skipped (seedData=false). Database ${dbName} will be empty!`);
      }
    } catch (dbError) {
      logger.error(`❌ Error initializing tenant database for ${dbName}: ${dbError.message}`);
      logger.error(`Stack trace: ${dbError.stack}`);

      // Return error response since database creation failed
      return res.status(500).json({
        success: false,
        message: 'Organization created but database initialization failed',
        error: dbError.message,
        organization: {
          id: organization._id,
          name: organization.name,
          dbName: dbName,
        },
      });
    }

    res.status(201).json({
      success: true,
      message: 'Organization created successfully with isolated database',
      data: {
        ...organization.toObject(),
        database: {
          name: dbName,
          initialized: dbInitialized,
          seeded: seedData && seedingResult !== null,
          seedingData: seedingResult?.data || null,
        },
      },
    });

  } catch (error) {
    logger.error(`Create organization error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error creating organization',
      error: error.message,
    });
  }
};

/**
 * @desc    Get all organizations
 * @route   GET /api/admin/organizations
 * @access  Private/SuperAdmin
 */
exports.getAllOrganizations = async (req, res) => {
  try {
    const { page = 1, limit = 10, status, search, includeInactive } = req.query;

    const query = {};

    // By default, only show active organizations unless includeInactive is set
    if (includeInactive !== 'true') {
      query.isActive = true;
    }

    if (status) {
      query.subscriptionStatus = status;
    }

    if (search) {
      query.$or = [
        { name: { $regex: search, $options: 'i' } },
        { email: { $regex: search, $options: 'i' } },
        { slug: { $regex: search, $options: 'i' } },
      ];
    }

    const organizations = await Organization.find(query)
      .populate('enabledFeatures.featureId')
      .sort({ createdAt: -1 })
      .limit(limit * 1)
      .skip((page - 1) * limit)
      .select('-adminUser.password');

    const count = await Organization.countDocuments(query);

    res.status(200).json({
      success: true,
      data: organizations,
      pagination: {
        total: count,
        page: parseInt(page),
        pages: Math.ceil(count / limit),
      },
    });

  } catch (error) {
    logger.error(`Get organizations error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error fetching organizations',
      error: error.message,
    });
  }
};

/**
 * @desc    Get single organization
 * @route   GET /api/admin/organizations/:id
 * @access  Private/SuperAdmin
 */
exports.getOrganization = async (req, res) => {
  try {
    const organization = await Organization.findById(req.params.id)
      .populate('enabledFeatures.featureId')
      .select('-adminUser.password');

    if (!organization) {
      return res.status(404).json({
        success: false,
        message: 'Organization not found',
      });
    }

    res.status(200).json({
      success: true,
      data: organization,
    });

  } catch (error) {
    logger.error(`Get organization error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error fetching organization',
      error: error.message,
    });
  }
};

/**
 * @desc    Update organization
 * @route   PUT /api/admin/organizations/:id
 * @access  Private/SuperAdmin
 */
exports.updateOrganization = async (req, res) => {
  try {
    let organization = await Organization.findById(req.params.id).select('+adminUser.password');

    if (!organization) {
      return res.status(404).json({
        success: false,
        message: 'Organization not found',
      });
    }

    // Update fields
    const updateFields = [
      'name', 'phone', 'address', 'settings', 'limits',
      'subscriptionPlan', 'subscriptionStatus', 'subscriptionEndDate',
      'isActive', 'branding', 'notes'
    ];

    updateFields.forEach(field => {
      if (req.body[field] !== undefined) {
        organization[field] = req.body[field];
      }
    });

    // Handle Admin User updates
    if (req.body.adminUser) {
      if (req.body.adminUser.firstName) organization.adminUser.firstName = req.body.adminUser.firstName;
      if (req.body.adminUser.lastName) organization.adminUser.lastName = req.body.adminUser.lastName;
      if (req.body.adminUser.email) organization.adminUser.email = req.body.adminUser.email;
      if (req.body.adminUser.phone) organization.adminUser.phone = req.body.adminUser.phone;
      if (req.body.adminUser.password) {
        console.log('🔑 [Update] New password provided for:', organization.adminUser.email);
        organization.adminUser.password = req.body.adminUser.password;
        organization.markModified('adminUser.password'); // Force Mongoose to notice the change
      }
    }

    console.log('📝 [Update] Organization modification status:', organization.isModified('adminUser.password'));

    if (req.user && req.user._id && mongoose.Types.ObjectId.isValid(req.user._id)) {
      organization.lastModifiedBy = req.user._id;
    }
    await organization.save();

    logger.info(`Organization updated: ${organization.name} by ${req.user.email}`);

    res.status(200).json({
      success: true,
      message: 'Organization updated successfully',
      data: organization,
    });

  } catch (error) {
    console.error('❌ [Update Organization Error]:', error);
    logger.error(`Update organization error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error updating organization: ' + error.message,
      error: error.stack,
    });
  }
};

/**
 * @desc    Update organization features (Enable/Disable modules)
 * @route   PUT /api/admin/organizations/:id/features
 * @access  Private/SuperAdmin
 */
exports.updateOrganizationFeatures = async (req, res) => {
  try {
    const { enabledFeatures } = req.body;

    if (!enabledFeatures || !Array.isArray(enabledFeatures)) {
      return res.status(400).json({
        success: false,
        message: 'enabledFeatures must be an array',
      });
    }

    let organization = await Organization.findById(req.params.id);

    if (!organization) {
      return res.status(404).json({
        success: false,
        message: 'Organization not found',
      });
    }

    // Validate feature IDs if there are any features to enable
    if (enabledFeatures.length > 0) {
      const featureIds = enabledFeatures.map(f => f.featureId);
      const features = await Feature.find({ _id: { $in: featureIds } });

      if (features.length !== featureIds.length) {
        logger.error(`Feature validation failed. Provided: ${featureIds.length}, Found: ${features.length}`);
        return res.status(400).json({
          success: false,
          message: 'One or more invalid feature IDs',
          details: {
            provided: featureIds.length,
            valid: features.length,
          }
        });
      }
    }

    organization.enabledFeatures = enabledFeatures;
    organization.lastModifiedBy = req.user._id;
    await organization.save();

    logger.info(`Features updated for organization: ${organization.name} (${enabledFeatures.length} features) by ${req.user.email}`);

    res.status(200).json({
      success: true,
      message: 'Features updated successfully',
      data: organization,
    });

  } catch (error) {
    logger.error(`Update features error: ${error.message}`);
    logger.error(`Stack: ${error.stack}`);
    res.status(500).json({
      success: false,
      message: 'Error updating features',
      error: error.message,
    });
  }
};

/**
 * @desc    Delete organization
 * @route   DELETE /api/admin/organizations/:id
 * @access  Private/SuperAdmin
 */
exports.deleteOrganization = async (req, res) => {
  try {
    const organization = await Organization.findById(req.params.id);

    if (!organization) {
      return res.status(404).json({
        success: false,
        message: 'Organization not found',
      });
    }

    // Soft delete - just deactivate
    organization.isActive = false;
    organization.subscriptionStatus = 'CANCELLED';
    organization.lastModifiedBy = req.user._id;
    await organization.save();

    logger.warn(`Organization deactivated: ${organization.name} by ${req.user.email}`);

    res.status(200).json({
      success: true,
      message: 'Organization deactivated successfully',
    });

  } catch (error) {
    logger.error(`Delete organization error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error deleting organization',
      error: error.message,
    });
  }
};

/**
 * @desc    Get all available features
 * @route   GET /api/admin/features
 * @access  Private/SuperAdmin
 */
exports.getAllFeatures = async (req, res) => {
  try {
    const features = await Feature.find({ isActive: true })
      .sort({ category: 1, displayOrder: 1 });

    res.status(200).json({
      success: true,
      count: features.length,
      data: features,
    });

  } catch (error) {
    logger.error(`Get features error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error fetching features',
      error: error.message,
    });
  }
};

/**
 * @desc    Create feature
 * @route   POST /api/admin/features
 * @access  Private/SuperAdmin
 */
exports.createFeature = async (req, res) => {
  try {
    const feature = await Feature.create(req.body);

    logger.info(`Feature created: ${feature.name} by ${req.user.email}`);

    res.status(201).json({
      success: true,
      message: 'Feature created successfully',
      data: feature,
    });

  } catch (error) {
    logger.error(`Create feature error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error creating feature',
      error: error.message,
    });
  }
};

/**
 * @desc    Add secondary admin to organization
 * @route   POST /api/admin/organizations/:id/admins
 * @access  Private/SuperAdmin
 */
exports.addSecondaryAdmin = async (req, res) => {
  try {
    const { firstName, lastName, email, phone, password } = req.body;

    if (!firstName || !lastName || !email || !password) {
      return res.status(400).json({ success: false, message: 'Missing required fields' });
    }

    const organization = await Organization.findById(req.params.id);
    if (!organization) {
      return res.status(404).json({ success: false, message: 'Organization not found' });
    }

    // Check if email already exists in primary or secondary admins
    const isPrimary = organization.adminUser.email === email.toLowerCase();
    const isSecondary = organization.secondaryAdmins.some(admin => admin.email === email.toLowerCase());

    if (isPrimary || isSecondary) {
      return res.status(400).json({ success: false, message: 'Admin with this email already exists' });
    }

    organization.secondaryAdmins.push({
      firstName,
      lastName,
      email: email.toLowerCase(),
      phone,
      password,
      isActive: true
    });

    await organization.save();

    res.status(200).json({
      success: true,
      message: 'Secondary admin added successfully',
      data: organization.secondaryAdmins
    });
  } catch (error) {
    logger.error('Add secondary admin error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * @desc    Update secondary admin details
 * @route   PUT /api/admin/organizations/:id/admins/:adminId
 * @access  Private/SuperAdmin
 */
exports.updateSecondaryAdmin = async (req, res) => {
  try {
    const { firstName, lastName, email, phone, password } = req.body;
    const organization = await Organization.findById(req.params.id);

    if (!organization) {
      return res.status(404).json({ success: false, message: 'Organization not found' });
    }

    const adminIndex = organization.secondaryAdmins.findIndex(
      admin => admin._id.toString() === req.params.adminId
    );

    if (adminIndex === -1) {
      return res.status(404).json({ success: false, message: 'Admin not found' });
    }

    // Update fields
    if (firstName) organization.secondaryAdmins[adminIndex].firstName = firstName;
    if (lastName) organization.secondaryAdmins[adminIndex].lastName = lastName;
    if (email) organization.secondaryAdmins[adminIndex].email = email.toLowerCase();
    if (phone) organization.secondaryAdmins[adminIndex].phone = phone;

    if (password) {
      organization.secondaryAdmins[adminIndex].password = password;
      organization.markModified(`secondaryAdmins.${adminIndex}.password`);
    }

    await organization.save();

    res.status(200).json({
      success: true,
      message: 'Secondary admin updated successfully',
      data: organization.secondaryAdmins
    });
  } catch (error) {
    logger.error('Update secondary admin error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * @desc    Remove secondary admin from organization
 * @route   DELETE /api/admin/organizations/:id/admins/:email
 * @access  Private/SuperAdmin
 */
exports.removeSecondaryAdmin = async (req, res) => {
  try {
    const organization = await Organization.findById(req.params.id);
    if (!organization) {
      return res.status(404).json({ success: false, message: 'Organization not found' });
    }

    organization.secondaryAdmins = organization.secondaryAdmins.filter(
      admin => admin.email !== req.params.email.toLowerCase()
    );

    await organization.save();

    res.status(200).json({
      success: true,
      message: 'Admin removed successfully',
      data: organization.secondaryAdmins
    });
  } catch (error) {
    logger.error('Remove secondary admin error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * @desc    Get all payment history across all organizations
 * @route   GET /api/admin/payments
 * @access  Private/SuperAdmin
 */
exports.getAllPaymentHistory = async (req, res) => {
  try {
    const Subscription = require('../models/shared/Subscription');

    const payments = await Subscription.aggregate([
      { $unwind: '$paymentHistory' },
      {
        $lookup: {
          from: 'organizations',
          localField: 'organizationId',
          foreignField: '_id',
          as: 'organization'
        }
      },
      { $unwind: '$organization' },
      {
        $project: {
          _id: '$paymentHistory._id',
          organizationId: 1,
          organizationName: '$organization.name',
          amount: '$paymentHistory.amount',
          plan: '$paymentHistory.plan',
          type: '$paymentHistory.type',
          paymentDate: '$paymentHistory.paymentDate',
          transactionId: '$paymentHistory.transactionId',
          paymentMethod: '$paymentHistory.paymentMethod',
          paymentStatus: '$paymentHistory.paymentStatus',
          description: '$paymentHistory.description'
        }
      },
      { $sort: { paymentDate: -1 } }
    ]);

    res.status(200).json({
      success: true,
      data: payments
    });
  } catch (error) {
    logger.error('Get all payments error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * @desc    Get all organizations with detailed subscription info
 * @route   GET /api/admin/subscriptions
 * @access  Private/SuperAdmin
 */
exports.getAllSubscriptionDetails = async (req, res) => {
  try {
    const Organization = require('../models/shared/Organization');

    const subscriptions = await Organization.aggregate([
      {
        $lookup: {
          from: 'subscriptions',
          localField: '_id',
          foreignField: 'organizationId',
          as: 'subscription'
        }
      },
      {
        $unwind: {
          path: '$subscription',
          preserveNullAndEmptyArrays: true
        }
      },
      {
        $project: {
          _id: 1,
          name: 1,
          email: 1,
          phone: 1, // Added phone for contact
          logo: '$branding.logo',
          subscription: {
            status: { $ifNull: ['$subscription.status', 'inactive'] },
            plan: { $ifNull: ['$subscription.plan', 'Free'] },
            planPrice: '$subscription.planPrice',
            startDate: '$subscription.startDate',
            endDate: '$subscription.endDate',
            autoRenew: '$subscription.autoRenew',
            // Token Details
            freeTokens: '$subscription.freeTokens',
            purchasedTokens: '$subscription.purchasedTokens',
            // Payment History for this org
            paymentHistory: '$subscription.paymentHistory'
          }
        }
      },
      { $sort: { 'subscription.endDate': 1 } } // Sort by expiry date (soonest first)
    ]);

    res.status(200).json({
      success: true,
      data: subscriptions
    });
  } catch (error) {
    logger.error('Get subscription details error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * @desc    Get system statistics
 * @route   GET /api/admin/stats
 * @access  Private/SuperAdmin
 */
exports.getSystemStats = async (req, res) => {
  try {
    const totalOrganizations = await Organization.countDocuments();
    const activeOrganizations = await Organization.countDocuments({
      isActive: true,
      subscriptionStatus: 'ACTIVE'
    });
    const trialOrganizations = await Organization.countDocuments({
      subscriptionPlan: 'TRIAL'
    });

    const stats = {
      totalOrganizations,
      activeOrganizations,
      inactiveOrganizations: totalOrganizations - activeOrganizations,
      trialOrganizations,
      organizationsByPlan: await Organization.aggregate([
        { $group: { _id: '$subscriptionPlan', count: { $sum: 1 } } }
      ]),
      organizationsByStatus: await Organization.aggregate([
        { $group: { _id: '$subscriptionStatus', count: { $sum: 1 } } }
      ]),
    };

    res.status(200).json({
      success: true,
      data: stats,
    });

  } catch (error) {
    logger.error(`Get stats error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: 'Error fetching statistics',
      error: error.message,
    });
  }
};
