const mongoose = require('mongoose');
const Customer = require('../models/vlite/Customer');

const ORG_ID = '674ac2767b7e5917034c6931';

const customers = [
  {
    organizationId: ORG_ID,
    customerCode: 'CUST001',
    type: 'BUSINESS',
    companyName: 'ABC Furniture Pvt Ltd',
    firstName: 'Rajesh',
    lastName: 'Kumar',
    email: 'rajesh@abcfurniture.com',
    phone: '+91-9876543210',
    address: {
      street: '123 MG Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      zipCode: '400001'
    },
    gstNumber: '27AABCU9603R1ZM',
    panNumber: 'AABCU9603R',
    source: 'DEALER',
    creditLimit: 500000,
    creditDays: 30,
    status: 'ACTIVE'
  },
  {
    organizationId: ORG_ID,
    customerCode: 'CUST002',
    type: 'BUSINESS',
    companyName: 'XYZ Interior Solutions',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya@xyzinteriors.com',
    phone: '+91-9876543211',
    address: {
      street: '456 Park Street',
      city: 'Kolkata',
      state: 'West Bengal',
      zipCode: '700016'
    },
    gstNumber: '19AABCX9603R1ZN',
    panNumber: 'AABCX9603R',
    source: 'REFERRAL',
    creditLimit: 300000,
    creditDays: 15,
    status: 'ACTIVE'
  },
  {
    organizationId: ORG_ID,
    customerCode: 'CUST003',
    type: 'DEALER',
    companyName: 'Modern Home Decor',
    firstName: 'Amit',
    lastName: 'Patel',
    email: 'amit@modernhomedecor.com',
    phone: '+91-9876543212',
    address: {
      street: '789 Commercial Street',
      city: 'Bangalore',
      state: 'Karnataka',
      zipCode: '560001'
    },
    gstNumber: '29AABCM9603R1ZO',
    panNumber: 'AABCM9603R',
    source: 'DEALER',
    creditLimit: 750000,
    creditDays: 45,
    status: 'ACTIVE'
  },
  {
    organizationId: ORG_ID,
    customerCode: 'CUST004',
    type: 'BUSINESS',
    companyName: 'Elite Furniture House',
    firstName: 'Sunita',
    lastName: 'Verma',
    email: 'sunita@elitefurniture.com',
    phone: '+91-9876543213',
    address: {
      street: '321 Nehru Place',
      city: 'Delhi',
      state: 'Delhi',
      zipCode: '110019'
    },
    gstNumber: '07AABCE9603R1ZP',
    panNumber: 'AABCE9603R',
    source: 'WALK_IN',
    creditLimit: 1000000,
    creditDays: 60,
    status: 'ACTIVE'
  },
  {
    organizationId: ORG_ID,
    customerCode: 'CUST005',
    type: 'INDIVIDUAL',
    firstName: 'Vikram',
    lastName: 'Singh',
    email: 'vikram@royalinteriors.com',
    phone: '+91-9876543214',
    address: {
      street: '555 Station Road',
      city: 'Pune',
      state: 'Maharashtra',
      zipCode: '411001'
    },
    gstNumber: '27AABCR9603R1ZQ',
    panNumber: 'AABCR9603R',
    source: 'WEBSITE',
    creditLimit: 250000,
    creditDays: 30,
    status: 'ACTIVE'
  }
];

async function seedCustomers() {
  try {
    await mongoose.connect('mongodb://localhost:27017/erp_system');
    console.log('Connected to MongoDB');

    // Clear existing customers for this org
    await Customer.deleteMany({ organizationId: ORG_ID });
    console.log('Cleared existing customers');

    // Insert new customers
    const result = await Customer.insertMany(customers);
    console.log(`✅ Successfully added ${result.length} customers`);

    // Display added customers
    result.forEach((customer, index) => {
      console.log(`${index + 1}. ${customer.companyName || `${customer.firstName} ${customer.lastName}`} - ${customer.customerCode}`);
    });

    process.exit(0);
  } catch (error) {
    console.error('Error seeding customers:', error);
    process.exit(1);
  }
}

seedCustomers();
require('dotenv').config();
const mongoose = require('mongoose');
const Customer = require('../models/vlite/Customer');
const Organization = require('../models/shared/Organization');
const connectDB = require('../config/database');

const sampleCustomers = [
  {
    customerCode: 'CUST-2024-001',
    companyName: 'Premium Interiors Pvt Ltd',
    tradeName: 'Premium Interiors',
    customerType: 'Dealer',
    status: 'Active',
    registrationDate: new Date('2024-01-15'),
    creditLimit: 500000,
    creditDays: 45,
    website: 'www.premiuminteriors.com',
    gstNumber: '29ABCDE1234F1Z5',
    panNumber: 'ABCDE1234F',
    gstType: 'Regular',
    registeredState: 'Karnataka',
    billingAddress: {
      address: '123, MG Road, Richmond Town',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560025',
      country: 'India',
    },
    officeAddress: {
      address: '456, Brigade Road, Commercial Street',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560001',
      country: 'India',
    },
    workAddress: {
      address: '789, Industrial Area, Peenya',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560058',
      country: 'India',
    },
    emails: [
      { email: 'info@premiuminteriors.com', type: 'Primary' },
      { email: 'accounts@premiuminteriors.com', type: 'Accounts' },
      { email: 'purchase@premiuminteriors.com', type: 'Purchase' },
    ],
    phoneNumbers: [
      { number: '+91 80 2345 6789', type: 'Office' },
      { number: '+91 80 2345 6790', type: 'Alternate' },
    ],
    contactPersons: [
      {
        name: 'Rajesh Kumar',
        designation: 'Managing Director',
        email: 'rajesh@premiuminteriors.com',
        mobile: '+91 98450 12345',
        isPrimary: true,
      },
      {
        name: 'Priya Sharma',
        designation: 'Purchase Manager',
        email: 'priya@premiuminteriors.com',
        mobile: '+91 98450 67890',
        isPrimary: false,
      },
    ],
    categories: {
      panel: {
        enabled: true,
        discount: 12,
        creditLimit: 200000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Century Ply', 'Green Ply', 'Action Tesa'],
        notes: 'High volume dealer for premium panels',
      },
      laminate: {
        enabled: true,
        discount: 15,
        creditLimit: 150000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['Merino', 'Greenlam', 'Royale Touché'],
        notes: 'Focus on designer laminates',
      },
      edgeband: {
        enabled: true,
        discount: 10,
        creditLimit: 50000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Rehau', 'IFP', 'Greenlam'],
        notes: 'Regular orders for matching edgebands',
      },
      hardware: {
        enabled: true,
        discount: 18,
        creditLimit: 300000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Hettich', 'Ebco', 'Hafele', 'Blum'],
        notes: 'Premium hardware specialist',
      },
      glass: {
        enabled: false,
        discount: 0,
        creditLimit: 0,
        paymentTerms: 'NA',
        preferredBrands: [],
        notes: 'Not dealing in glass currently',
      },
      fabric: {
        enabled: true,
        discount: 8,
        creditLimit: 75000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['Sunbrella', 'Warwick', 'Sahco'],
        notes: 'Upholstery fabric requirements',
      },
      aluminium: {
        enabled: true,
        discount: 10,
        creditLimit: 100000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Jindal', 'Hindalco', 'Fenesta'],
        notes: 'Aluminium profiles for modular kitchens',
      },
      service: {
        enabled: true,
        discount: 5,
        creditLimit: 50000,
        paymentTerms: 'Advance Payment',
        serviceTypes: ['Installation', 'Repair', 'Maintenance'],
        notes: 'Regular AMC customer',
      },
    },
    totalOrders: 45,
    totalRevenue: 2500000,
    lastOrderDate: new Date('2024-11-28'),
    outstandingAmount: 125000,
    remarks: 'Excellent payment track record',
  },
  {
    customerCode: 'CUST-2024-002',
    companyName: 'Urban Living Spaces',
    tradeName: 'Urban Living',
    customerType: 'Distributor',
    status: 'Active',
    registrationDate: new Date('2024-02-10'),
    creditLimit: 1000000,
    creditDays: 60,
    website: 'www.urbanliving.in',
    gstNumber: '27XYZAB5678G1Z9',
    panNumber: 'XYZAB5678G',
    gstType: 'Regular',
    registeredState: 'Maharashtra',
    billingAddress: {
      address: '234, Andheri Link Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400053',
      country: 'India',
    },
    officeAddress: {
      address: '234, Andheri Link Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400053',
      country: 'India',
    },
    workAddress: {
      address: '567, MIDC Industrial Area',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400093',
      country: 'India',
    },
    emails: [
      { email: 'contact@urbanliving.in', type: 'Primary' },
      { email: 'billing@urbanliving.in', type: 'Accounts' },
    ],
    phoneNumbers: [
      { number: '+91 22 2345 6789', type: 'Office' },
    ],
    contactPersons: [
      {
        name: 'Amit Patel',
        designation: 'Director',
        email: 'amit@urbanliving.in',
        mobile: '+91 98765 43210',
        isPrimary: true,
      },
    ],
    categories: {
      panel: {
        enabled: true,
        discount: 15,
        creditLimit: 400000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Green Ply', 'Century Ply'],
        notes: 'Large distributor - high volume',
      },
      laminate: {
        enabled: true,
        discount: 18,
        creditLimit: 300000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Merino', 'Greenlam'],
        notes: 'Premium laminate distributor',
      },
      edgeband: {
        enabled: false,
      },
      hardware: {
        enabled: true,
        discount: 20,
        creditLimit: 500000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Hettich', 'Hafele', 'Blum'],
        notes: 'Authorized distributor for major brands',
      },
      glass: {
        enabled: true,
        discount: 12,
        creditLimit: 200000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Saint Gobain', 'AIS'],
        notes: 'Glass and mirror specialist',
      },
      fabric: {
        enabled: false,
      },
      aluminium: {
        enabled: false,
      },
      service: {
        enabled: false,
      },
    },
    totalOrders: 78,
    totalRevenue: 5200000,
    lastOrderDate: new Date('2024-12-05'),
    outstandingAmount: 450000,
    remarks: 'Top distributor - VIP customer',
  },
  {
    customerCode: 'CUST-2024-003',
    companyName: 'Classic Furniture Hub',
    tradeName: 'Classic Hub',
    customerType: 'Retailer',
    status: 'Active',
    registrationDate: new Date('2024-03-20'),
    creditLimit: 300000,
    creditDays: 30,
    website: '',
    gstNumber: '33PQRCD9012H1Z3',
    panNumber: 'PQRCD9012H',
    gstType: 'Regular',
    registeredState: 'Tamil Nadu',
    billingAddress: {
      address: '45, T Nagar Main Road',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600017',
      country: 'India',
    },
    officeAddress: {
      address: '45, T Nagar Main Road',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600017',
      country: 'India',
    },
    workAddress: {
      address: '45, T Nagar Main Road',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600017',
      country: 'India',
    },
    emails: [
      { email: 'classichub@gmail.com', type: 'Primary' },
    ],
    phoneNumbers: [
      { number: '+91 44 2345 6789', type: 'Office' },
      { number: '+91 98400 12345', type: 'Mobile' },
    ],
    contactPersons: [
      {
        name: 'Sundar Rajan',
        designation: 'Owner',
        email: 'sundar@classichub.com',
        mobile: '+91 98400 12345',
        isPrimary: true,
      },
    ],
    categories: {
      panel: {
        enabled: true,
        discount: 8,
        creditLimit: 100000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['Green Ply'],
        notes: 'Local retailer - steady orders',
      },
      laminate: {
        enabled: true,
        discount: 10,
        creditLimit: 80000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['Greenlam'],
        notes: 'Mid-range laminates preferred',
      },
      edgeband: {
        enabled: true,
        discount: 8,
        creditLimit: 30000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['IFP'],
        notes: '',
      },
      hardware: {
        enabled: true,
        discount: 12,
        creditLimit: 120000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['Ebco', 'Hettich'],
        notes: 'Standard hardware range',
      },
      glass: {
        enabled: false,
      },
      fabric: {
        enabled: true,
        discount: 5,
        creditLimit: 50000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['Local suppliers'],
        notes: '',
      },
      aluminium: {
        enabled: false,
      },
      service: {
        enabled: false,
      },
    },
    totalOrders: 23,
    totalRevenue: 850000,
    lastOrderDate: new Date('2024-12-01'),
    outstandingAmount: 65000,
  },
  {
    customerCode: 'CUST-2024-004',
    companyName: 'Metro Furniture Solutions Pvt Ltd',
    tradeName: 'Metro Furniture',
    customerType: 'Contractor',
    status: 'Active',
    registrationDate: new Date('2024-04-15'),
    creditLimit: 750000,
    creditDays: 45,
    website: 'www.metrofurniture.co.in',
    gstNumber: '07GHIJK3456L1Z8',
    panNumber: 'GHIJK3456L',
    gstType: 'Regular',
    registeredState: 'Delhi',
    billingAddress: {
      address: '67, Okhla Industrial Estate, Phase 3',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110020',
      country: 'India',
    },
    officeAddress: {
      address: '89, Connaught Place',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110001',
      country: 'India',
    },
    workAddress: {
      address: '67, Okhla Industrial Estate, Phase 3',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110020',
      country: 'India',
    },
    emails: [
      { email: 'info@metrofurniture.co.in', type: 'Primary' },
      { email: 'projects@metrofurniture.co.in', type: 'Other' },
    ],
    phoneNumbers: [
      { number: '+91 11 4567 8901', type: 'Office' },
      { number: '+91 11 4567 8902', type: 'Fax' },
    ],
    contactPersons: [
      {
        name: 'Vikram Singh',
        designation: 'Project Manager',
        email: 'vikram@metrofurniture.co.in',
        mobile: '+91 98111 23456',
        isPrimary: true,
      },
    ],
    categories: {
      panel: {
        enabled: true,
        discount: 14,
        creditLimit: 250000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Century Ply', 'Action Tesa'],
        notes: 'Large project orders',
      },
      laminate: {
        enabled: true,
        discount: 16,
        creditLimit: 200000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Greenlam', 'Merino'],
        notes: 'Commercial grade laminates',
      },
      edgeband: {
        enabled: true,
        discount: 12,
        creditLimit: 80000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Rehau', 'Greenlam'],
        notes: '',
      },
      hardware: {
        enabled: true,
        discount: 16,
        creditLimit: 350000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Hettich', 'Hafele', 'Ebco'],
        notes: 'Bulk orders for projects',
      },
      glass: {
        enabled: true,
        discount: 10,
        creditLimit: 150000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Saint Gobain'],
        notes: 'For cabinet doors',
      },
      fabric: {
        enabled: false,
      },
      aluminium: {
        enabled: true,
        discount: 12,
        creditLimit: 180000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Jindal', 'Hindalco'],
        notes: 'Modular kitchen projects',
      },
      service: {
        enabled: true,
        discount: 8,
        creditLimit: 100000,
        paymentTerms: 'Net 30 Days',
        serviceTypes: ['Installation', 'Project Management'],
        notes: 'End-to-end project services',
      },
    },
    totalOrders: 34,
    totalRevenue: 3200000,
    lastOrderDate: new Date('2024-11-30'),
    outstandingAmount: 280000,
    remarks: 'Government and corporate projects specialist',
  },
  {
    customerCode: 'CUST-2024-005',
    companyName: 'Royal Decor International',
    tradeName: 'Royal Decor',
    customerType: 'Dealer',
    status: 'Active',
    registrationDate: new Date('2024-05-10'),
    creditLimit: 600000,
    creditDays: 60,
    website: 'www.royaldecor.com',
    gstNumber: '24MNOPQ7890R1Z2',
    panNumber: 'MNOPQ7890R',
    gstType: 'Regular',
    registeredState: 'Gujarat',
    billingAddress: {
      address: '123, CG Road, Navrangpura',
      city: 'Ahmedabad',
      state: 'Gujarat',
      pincode: '380009',
      country: 'India',
    },
    officeAddress: {
      address: '123, CG Road, Navrangpura',
      city: 'Ahmedabad',
      state: 'Gujarat',
      pincode: '380009',
      country: 'India',
    },
    workAddress: {
      address: '456, GIDC Estate, Vatva',
      city: 'Ahmedabad',
      state: 'Gujarat',
      pincode: '382445',
      country: 'India',
    },
    emails: [
      { email: 'sales@royaldecor.com', type: 'Primary' },
      { email: 'accounts@royaldecor.com', type: 'Accounts' },
    ],
    phoneNumbers: [
      { number: '+91 79 2345 6789', type: 'Office' },
      { number: '+91 98250 12345', type: 'Mobile' },
    ],
    contactPersons: [
      {
        name: 'Mehul Shah',
        designation: 'Proprietor',
        email: 'mehul@royaldecor.com',
        mobile: '+91 98250 12345',
        isPrimary: true,
      },
      {
        name: 'Neha Shah',
        designation: 'Manager',
        email: 'neha@royaldecor.com',
        mobile: '+91 98250 67890',
        isPrimary: false,
      },
    ],
    categories: {
      panel: {
        enabled: true,
        discount: 13,
        creditLimit: 220000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Green Ply', 'Century Ply', 'Greenply Industries'],
        notes: 'Premium and commercial panels',
      },
      laminate: {
        enabled: true,
        discount: 16,
        creditLimit: 180000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Merino', 'Royale Touché', 'Greenlam'],
        notes: 'Designer collection focus',
      },
      edgeband: {
        enabled: true,
        discount: 11,
        creditLimit: 60000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Rehau', 'IFP'],
        notes: '',
      },
      hardware: {
        enabled: true,
        discount: 19,
        creditLimit: 280000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Hettich', 'Blum', 'Hafele', 'Grass'],
        notes: 'Premium hardware dealer',
      },
      glass: {
        enabled: false,
      },
      fabric: {
        enabled: true,
        discount: 10,
        creditLimit: 90000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Warwick', 'D Decor'],
        notes: 'Upholstery and curtains',
      },
      aluminium: {
        enabled: true,
        discount: 11,
        creditLimit: 140000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Fenesta', 'Jindal'],
        notes: 'Windows and kitchen profiles',
      },
      service: {
        enabled: true,
        discount: 6,
        creditLimit: 80000,
        paymentTerms: 'Advance Payment',
        serviceTypes: ['Installation', 'Design Consultation', 'Maintenance'],
        notes: 'Full service dealer',
      },
    },
    totalOrders: 56,
    totalRevenue: 3800000,
    lastOrderDate: new Date('2024-12-04'),
    outstandingAmount: 320000,
    remarks: 'Premium customer - VIP treatment',
  },
  {
    customerCode: 'CUST-2024-006',
    companyName: 'Modern Spaces LLP',
    tradeName: 'Modern Spaces',
    customerType: 'End Customer',
    status: 'Active',
    registrationDate: new Date('2024-06-20'),
    creditLimit: 200000,
    creditDays: 15,
    website: '',
    gstNumber: '36STUVW2345X1Z7',
    panNumber: 'STUVW2345X',
    gstType: 'Regular',
    registeredState: 'Telangana',
    billingAddress: {
      address: 'Plot 45, Banjara Hills',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500034',
      country: 'India',
    },
    officeAddress: {
      address: 'Plot 45, Banjara Hills',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500034',
      country: 'India',
    },
    workAddress: {
      address: 'Plot 45, Banjara Hills',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500034',
      country: 'India',
    },
    emails: [
      { email: 'modernspaces.hyd@gmail.com', type: 'Primary' },
    ],
    phoneNumbers: [
      { number: '+91 40 2345 6789', type: 'Office' },
    ],
    contactPersons: [
      {
        name: 'Arjun Reddy',
        designation: 'Owner',
        email: 'arjun.reddy@gmail.com',
        mobile: '+91 98490 12345',
        isPrimary: true,
      },
    ],
    categories: {
      panel: {
        enabled: true,
        discount: 5,
        creditLimit: 60000,
        paymentTerms: 'Net 15 Days',
        preferredBrands: ['Green Ply'],
        notes: 'Home renovation project',
      },
      laminate: {
        enabled: true,
        discount: 6,
        creditLimit: 50000,
        paymentTerms: 'Net 15 Days',
        preferredBrands: ['Greenlam'],
        notes: '',
      },
      edgeband: {
        enabled: false,
      },
      hardware: {
        enabled: true,
        discount: 8,
        creditLimit: 80000,
        paymentTerms: 'Net 15 Days',
        preferredBrands: ['Hettich', 'Ebco'],
        notes: 'Kitchen hardware',
      },
      glass: {
        enabled: false,
      },
      fabric: {
        enabled: true,
        discount: 5,
        creditLimit: 40000,
        paymentTerms: 'Net 15 Days',
        preferredBrands: ['Local suppliers'],
        notes: 'Sofa and curtain fabric',
      },
      aluminium: {
        enabled: false,
      },
      service: {
        enabled: true,
        discount: 0,
        creditLimit: 30000,
        paymentTerms: 'Cash',
        serviceTypes: ['Installation'],
        notes: 'One-time project',
      },
    },
    totalOrders: 3,
    totalRevenue: 185000,
    lastOrderDate: new Date('2024-11-15'),
    outstandingAmount: 35000,
    remarks: 'Residential customer - villa project',
  },
  {
    customerCode: 'CUST-2024-007',
    companyName: 'Elegant Furnishings',
    tradeName: 'Elegant',
    customerType: 'Retailer',
    status: 'Active',
    registrationDate: new Date('2024-07-05'),
    creditLimit: 400000,
    creditDays: 45,
    website: 'www.elegantfurnish.in',
    gstNumber: '32ABCXY4567Z1Z4',
    panNumber: 'ABCXY4567Z',
    gstType: 'Regular',
    registeredState: 'Kerala',
    billingAddress: {
      address: '234, MG Road, Palarivattom',
      city: 'Kochi',
      state: 'Kerala',
      pincode: '682025',
      country: 'India',
    },
    officeAddress: {
      address: '234, MG Road, Palarivattom',
      city: 'Kochi',
      state: 'Kerala',
      pincode: '682025',
      country: 'India',
    },
    workAddress: {
      address: '567, Infopark Road, Kakkanad',
      city: 'Kochi',
      state: 'Kerala',
      pincode: '682042',
      country: 'India',
    },
    emails: [
      { email: 'contact@elegantfurnish.in', type: 'Primary' },
      { email: 'sales@elegantfurnish.in', type: 'Sales' },
    ],
    phoneNumbers: [
      { number: '+91 484 234 5678', type: 'Office' },
      { number: '+91 98470 12345', type: 'Mobile' },
    ],
    contactPersons: [
      {
        name: 'Thomas George',
        designation: 'Managing Partner',
        email: 'thomas@elegantfurnish.in',
        mobile: '+91 98470 12345',
        isPrimary: true,
      },
      {
        name: 'Reshma Thomas',
        designation: 'Sales Head',
        email: 'reshma@elegantfurnish.in',
        mobile: '+91 98470 67890',
        isPrimary: false,
      },
    ],
    categories: {
      panel: {
        enabled: true,
        discount: 11,
        creditLimit: 150000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Green Ply', 'Century Ply'],
        notes: 'Regular retail customer',
      },
      laminate: {
        enabled: true,
        discount: 13,
        creditLimit: 120000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Merino', 'Greenlam', 'Royale Touché'],
        notes: 'Wide range stocked',
      },
      edgeband: {
        enabled: true,
        discount: 10,
        creditLimit: 40000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['IFP', 'Greenlam'],
        notes: '',
      },
      hardware: {
        enabled: true,
        discount: 15,
        creditLimit: 180000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Hettich', 'Ebco', 'Hafele'],
        notes: 'Hardware showroom',
      },
      glass: {
        enabled: true,
        discount: 8,
        creditLimit: 60000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['AIS'],
        notes: 'Cabinet glass doors',
      },
      fabric: {
        enabled: true,
        discount: 7,
        creditLimit: 70000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Sunbrella', 'Local weavers'],
        notes: 'Custom upholstery',
      },
      aluminium: {
        enabled: false,
      },
      service: {
        enabled: true,
        discount: 5,
        creditLimit: 50000,
        paymentTerms: 'Net 30 Days',
        serviceTypes: ['Installation', 'Repair'],
        notes: 'In-house service team',
      },
    },
    totalOrders: 41,
    totalRevenue: 1950000,
    lastOrderDate: new Date('2024-12-03'),
    outstandingAmount: 145000,
    remarks: 'Growing retail partner',
  },
  {
    customerCode: 'CUST-2024-008',
    companyName: 'Skyline Developers Pvt Ltd',
    tradeName: 'Skyline',
    customerType: 'Contractor',
    status: 'Active',
    registrationDate: new Date('2024-08-12'),
    creditLimit: 1500000,
    creditDays: 90,
    website: 'www.skylinedev.com',
    gstNumber: '27DEFGH8901I1Z6',
    panNumber: 'DEFGH8901I',
    gstType: 'Regular',
    registeredState: 'Maharashtra',
    billingAddress: {
      address: '890, Bandra Kurla Complex',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400051',
      country: 'India',
    },
    officeAddress: {
      address: '890, Bandra Kurla Complex',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400051',
      country: 'India',
    },
    workAddress: {
      address: 'Site Office, Mulund East',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400081',
      country: 'India',
    },
    emails: [
      { email: 'procurement@skylinedev.com', type: 'Primary' },
      { email: 'accounts@skylinedev.com', type: 'Accounts' },
      { email: 'projects@skylinedev.com', type: 'Other' },
    ],
    phoneNumbers: [
      { number: '+91 22 6789 0123', type: 'Office' },
      { number: '+91 22 6789 0124', type: 'Alternate' },
    ],
    contactPersons: [
      {
        name: 'Ramesh Iyer',
        designation: 'Procurement Head',
        email: 'ramesh@skylinedev.com',
        mobile: '+91 98200 12345',
        isPrimary: true,
      },
      {
        name: 'Sneha Desai',
        designation: 'Project Coordinator',
        email: 'sneha@skylinedev.com',
        mobile: '+91 98200 67890',
        isPrimary: false,
      },
    ],
    categories: {
      panel: {
        enabled: true,
        discount: 18,
        creditLimit: 600000,
        paymentTerms: 'Net 90 Days',
        preferredBrands: ['Green Ply', 'Century Ply', 'Action Tesa'],
        notes: 'Bulk orders for residential projects',
      },
      laminate: {
        enabled: true,
        discount: 20,
        creditLimit: 400000,
        paymentTerms: 'Net 90 Days',
        preferredBrands: ['Merino', 'Greenlam'],
        notes: 'Large scale requirements',
      },
      edgeband: {
        enabled: true,
        discount: 15,
        creditLimit: 150000,
        paymentTerms: 'Net 90 Days',
        preferredBrands: ['Rehau', 'IFP'],
        notes: '',
      },
      hardware: {
        enabled: true,
        discount: 22,
        creditLimit: 700000,
        paymentTerms: 'Net 90 Days',
        preferredBrands: ['Hettich', 'Hafele', 'Blum', 'Ebco'],
        notes: 'Premium hardware for apartments',
      },
      glass: {
        enabled: true,
        discount: 15,
        creditLimit: 250000,
        paymentTerms: 'Net 90 Days',
        preferredBrands: ['Saint Gobain', 'AIS'],
        notes: 'Shower doors and partitions',
      },
      fabric: {
        enabled: false,
      },
      aluminium: {
        enabled: true,
        discount: 18,
        creditLimit: 500000,
        paymentTerms: 'Net 90 Days',
        preferredBrands: ['Jindal', 'Hindalco', 'Fenesta'],
        notes: 'Windows, doors, modular kitchens',
      },
      service: {
        enabled: true,
        discount: 10,
        creditLimit: 300000,
        paymentTerms: 'Net 60 Days',
        serviceTypes: ['Installation', 'Project Management', 'Maintenance'],
        notes: 'Turnkey interior solutions',
      },
    },
    totalOrders: 89,
    totalRevenue: 12500000,
    lastOrderDate: new Date('2024-12-06'),
    outstandingAmount: 950000,
    remarks: 'Largest customer - strategic partner',
  },
  {
    customerCode: 'CUST-2024-009',
    companyName: 'Comfort Living',
    tradeName: 'Comfort Living',
    customerType: 'Dealer',
    status: 'Active',
    registrationDate: new Date('2024-09-01'),
    creditLimit: 350000,
    creditDays: 30,
    website: '',
    gstNumber: '19JKLMN5678O1Z3',
    panNumber: 'JKLMN5678O',
    gstType: 'Regular',
    registeredState: 'West Bengal',
    billingAddress: {
      address: '456, Park Street',
      city: 'Kolkata',
      state: 'West Bengal',
      pincode: '700016',
      country: 'India',
    },
    officeAddress: {
      address: '456, Park Street',
      city: 'Kolkata',
      state: 'West Bengal',
      pincode: '700016',
      country: 'India',
    },
    workAddress: {
      address: '789, EM Bypass, Kasba',
      city: 'Kolkata',
      state: 'West Bengal',
      pincode: '700107',
      country: 'India',
    },
    emails: [
      { email: 'info@comfortliving.co.in', type: 'Primary' },
    ],
    phoneNumbers: [
      { number: '+91 33 2345 6789', type: 'Office' },
      { number: '+91 98300 12345', type: 'Mobile' },
    ],
    contactPersons: [
      {
        name: 'Debashish Roy',
        designation: 'Owner',
        email: 'debashish@comfortliving.co.in',
        mobile: '+91 98300 12345',
        isPrimary: true,
      },
    ],
    categories: {
      panel: {
        enabled: true,
        discount: 10,
        creditLimit: 120000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['Green Ply', 'Greenply Industries'],
        notes: 'Local market dealer',
      },
      laminate: {
        enabled: true,
        discount: 12,
        creditLimit: 100000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['Greenlam', 'Merino'],
        notes: 'Mid-range products',
      },
      edgeband: {
        enabled: true,
        discount: 9,
        creditLimit: 35000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['IFP'],
        notes: '',
      },
      hardware: {
        enabled: true,
        discount: 13,
        creditLimit: 140000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['Hettich', 'Ebco'],
        notes: 'Standard hardware range',
      },
      glass: {
        enabled: false,
      },
      fabric: {
        enabled: true,
        discount: 6,
        creditLimit: 50000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['Local suppliers'],
        notes: '',
      },
      aluminium: {
        enabled: false,
      },
      service: {
        enabled: false,
      },
    },
    totalOrders: 18,
    totalRevenue: 720000,
    lastOrderDate: new Date('2024-11-25'),
    outstandingAmount: 85000,
  },
  {
    customerCode: 'CUST-2024-010',
    companyName: 'Innovation Interiors Pvt Ltd',
    tradeName: 'Innovation Interiors',
    customerType: 'Distributor',
    status: 'Active',
    registrationDate: new Date('2024-10-05'),
    creditLimit: 1200000,
    creditDays: 75,
    website: 'www.innovationinteriors.in',
    gstNumber: '09PQRST6789U1Z1',
    panNumber: 'PQRST6789U',
    gstType: 'Regular',
    registeredState: 'Uttar Pradesh',
    billingAddress: {
      address: '123, Gomti Nagar Extension',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      pincode: '226010',
      country: 'India',
    },
    officeAddress: {
      address: '123, Gomti Nagar Extension',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      pincode: '226010',
      country: 'India',
    },
    workAddress: {
      address: '456, Industrial Area, Chinhat',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      pincode: '226028',
      country: 'India',
    },
    emails: [
      { email: 'contact@innovationinteriors.in', type: 'Primary' },
      { email: 'billing@innovationinteriors.in', type: 'Accounts' },
      { email: 'purchase@innovationinteriors.in', type: 'Purchase' },
    ],
    phoneNumbers: [
      { number: '+91 522 234 5678', type: 'Office' },
      { number: '+91 522 234 5679', type: 'Alternate' },
    ],
    contactPersons: [
      {
        name: 'Sanjay Verma',
        designation: 'CEO',
        email: 'sanjay@innovationinteriors.in',
        mobile: '+91 98390 12345',
        isPrimary: true,
      },
      {
        name: 'Anjali Gupta',
        designation: 'Purchase Manager',
        email: 'anjali@innovationinteriors.in',
        mobile: '+91 98390 67890',
        isPrimary: false,
      },
      {
        name: 'Rahul Mishra',
        designation: 'Sales Manager',
        email: 'rahul@innovationinteriors.in',
        mobile: '+91 98390 11111',
        isPrimary: false,
      },
    ],
    categories: {
      panel: {
        enabled: true,
        discount: 17,
        creditLimit: 500000,
        paymentTerms: 'Net 75 Days',
        preferredBrands: ['Green Ply', 'Century Ply', 'Action Tesa', 'Greenply Industries'],
        notes: 'Regional distributor - UP & Bihar',
      },
      laminate: {
        enabled: true,
        discount: 19,
        creditLimit: 400000,
        paymentTerms: 'Net 75 Days',
        preferredBrands: ['Merino', 'Greenlam', 'Royale Touché', 'Century Laminates'],
        notes: 'Wide distribution network',
      },
      edgeband: {
        enabled: true,
        discount: 14,
        creditLimit: 120000,
        paymentTerms: 'Net 75 Days',
        preferredBrands: ['Rehau', 'IFP', 'Greenlam'],
        notes: '',
      },
      hardware: {
        enabled: true,
        discount: 21,
        creditLimit: 600000,
        paymentTerms: 'Net 75 Days',
        preferredBrands: ['Hettich', 'Hafele', 'Blum', 'Ebco', 'Grass'],
        notes: 'Authorized distributor',
      },
      glass: {
        enabled: true,
        discount: 13,
        creditLimit: 200000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Saint Gobain', 'AIS', 'Modi Glass'],
        notes: 'Architectural glass supplier',
      },
      fabric: {
        enabled: true,
        discount: 9,
        creditLimit: 100000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Warwick', 'Sunbrella'],
        notes: 'Contract furnishing',
      },
      aluminium: {
        enabled: true,
        discount: 15,
        creditLimit: 350000,
        paymentTerms: 'Net 75 Days',
        preferredBrands: ['Jindal', 'Hindalco', 'Fenesta', 'UPVC Systems'],
        notes: 'Complete fenestration solutions',
      },
      service: {
        enabled: true,
        discount: 8,
        creditLimit: 150000,
        paymentTerms: 'Net 45 Days',
        serviceTypes: ['Installation', 'Project Management', 'Design Consultation', 'Maintenance'],
        notes: 'Complete turnkey solutions provider',
      },
    },
    totalOrders: 67,
    totalRevenue: 8900000,
    lastOrderDate: new Date('2024-12-07'),
    outstandingAmount: 680000,
    remarks: 'Key distributor for North India region',
  },
  {
    customerCode: 'CUST-2024-011',
    companyName: 'Smart Homes Design Studio',
    tradeName: 'Smart Homes',
    customerType: 'Retailer',
    status: 'Inactive',
    registrationDate: new Date('2024-02-28'),
    creditLimit: 150000,
    creditDays: 30,
    website: 'www.smarthomesdesign.com',
    gstNumber: '22VWXYZ1234A1Z9',
    panNumber: 'VWXYZ1234A',
    gstType: 'Regular',
    registeredState: 'Chhattisgarh',
    billingAddress: {
      address: '78, Civil Lines',
      city: 'Raipur',
      state: 'Chhattisgarh',
      pincode: '492001',
      country: 'India',
    },
    officeAddress: {
      address: '78, Civil Lines',
      city: 'Raipur',
      state: 'Chhattisgarh',
      pincode: '492001',
      country: 'India',
    },
    workAddress: {
      address: '78, Civil Lines',
      city: 'Raipur',
      state: 'Chhattisgarh',
      pincode: '492001',
      country: 'India',
    },
    emails: [
      { email: 'info@smarthomesdesign.com', type: 'Primary' },
    ],
    phoneNumbers: [
      { number: '+91 771 234 5678', type: 'Office' },
    ],
    contactPersons: [
      {
        name: 'Deepak Agrawal',
        designation: 'Owner',
        email: 'deepak@smarthomesdesign.com',
        mobile: '+91 98270 12345',
        isPrimary: true,
      },
    ],
    categories: {
      panel: {
        enabled: true,
        discount: 7,
        creditLimit: 50000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['Green Ply'],
        notes: 'Small orders',
      },
      laminate: {
        enabled: true,
        discount: 8,
        creditLimit: 40000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['Greenlam'],
        notes: '',
      },
      edgeband: {
        enabled: false,
      },
      hardware: {
        enabled: true,
        discount: 10,
        creditLimit: 60000,
        paymentTerms: 'Net 30 Days',
        preferredBrands: ['Ebco'],
        notes: 'Basic range',
      },
      glass: {
        enabled: false,
      },
      fabric: {
        enabled: false,
      },
      aluminium: {
        enabled: false,
      },
      service: {
        enabled: false,
      },
    },
    totalOrders: 8,
    totalRevenue: 280000,
    lastOrderDate: new Date('2024-07-15'),
    outstandingAmount: 0,
    remarks: 'Account inactive - business closed',
  },
  {
    customerCode: 'CUST-2024-012',
    companyName: 'Luxury Living Spaces Pvt Ltd',
    tradeName: 'Luxury Living',
    customerType: 'Dealer',
    status: 'Active',
    registrationDate: new Date('2024-11-10'),
    creditLimit: 800000,
    creditDays: 60,
    website: 'www.luxuryliving.co.in',
    gstNumber: '20BCDEF2345G1Z5',
    panNumber: 'BCDEF2345G',
    gstType: 'Regular',
    registeredState: 'Jharkhand',
    billingAddress: {
      address: '234, Main Road, Bistupur',
      city: 'Jamshedpur',
      state: 'Jharkhand',
      pincode: '831001',
      country: 'India',
    },
    officeAddress: {
      address: '234, Main Road, Bistupur',
      city: 'Jamshedpur',
      state: 'Jharkhand',
      pincode: '831001',
      country: 'India',
    },
    workAddress: {
      address: '567, Adityapur Industrial Area',
      city: 'Jamshedpur',
      state: 'Jharkhand',
      pincode: '831013',
      country: 'India',
    },
    emails: [
      { email: 'sales@luxuryliving.co.in', type: 'Primary' },
      { email: 'accounts@luxuryliving.co.in', type: 'Accounts' },
    ],
    phoneNumbers: [
      { number: '+91 657 234 5678', type: 'Office' },
      { number: '+91 98350 12345', type: 'Mobile' },
    ],
    contactPersons: [
      {
        name: 'Rohit Kumar',
        designation: 'Director',
        email: 'rohit@luxuryliving.co.in',
        mobile: '+91 98350 12345',
        isPrimary: true,
      },
      {
        name: 'Kavita Singh',
        designation: 'Design Head',
        email: 'kavita@luxuryliving.co.in',
        mobile: '+91 98350 67890',
        isPrimary: false,
      },
    ],
    categories: {
      panel: {
        enabled: true,
        discount: 14,
        creditLimit: 280000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Century Ply', 'Green Ply', 'Action Tesa'],
        notes: 'Premium panels for luxury projects',
      },
      laminate: {
        enabled: true,
        discount: 17,
        creditLimit: 250000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Merino', 'Royale Touché', 'Greenlam'],
        notes: 'High-end designer laminates',
      },
      edgeband: {
        enabled: true,
        discount: 13,
        creditLimit: 90000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Rehau', 'IFP'],
        notes: 'Premium edgebanding',
      },
      hardware: {
        enabled: true,
        discount: 20,
        creditLimit: 400000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Blum', 'Hettich', 'Hafele', 'Grass', 'Salice'],
        notes: 'Luxury hardware specialist',
      },
      glass: {
        enabled: true,
        discount: 12,
        creditLimit: 180000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Saint Gobain', 'AIS'],
        notes: 'Decorative and frosted glass',
      },
      fabric: {
        enabled: true,
        discount: 11,
        creditLimit: 120000,
        paymentTerms: 'Net 45 Days',
        preferredBrands: ['Sunbrella', 'Warwick', 'Sahco', 'D Decor'],
        notes: 'Premium upholstery fabrics',
      },
      aluminium: {
        enabled: true,
        discount: 14,
        creditLimit: 200000,
        paymentTerms: 'Net 60 Days',
        preferredBrands: ['Fenesta', 'Jindal', 'Hindalco'],
        notes: 'Luxury profiles and systems',
      },
      service: {
        enabled: true,
        discount: 7,
        creditLimit: 100000,
        paymentTerms: 'Net 30 Days',
        serviceTypes: ['Installation', 'Design Consultation', 'Project Management', 'Repair', 'Maintenance'],
        notes: 'Full-service luxury dealer',
      },
    },
    totalOrders: 12,
    totalRevenue: 1450000,
    lastOrderDate: new Date('2024-12-02'),
    outstandingAmount: 180000,
    remarks: 'New premium dealer - high potential',
  },
];

const seedCustomers = async () => {
  try {
    await connectDB();
    console.log('✅ Connected to database');

    // Get the first organization
    const organization = await Organization.findOne();
    if (!organization) {
      console.error('❌ No organization found. Please create an organization first.');
      process.exit(1);
    }

    console.log(`📋 Using organization: ${organization.name}`);

    // Delete existing customers for this organization
    await Customer.deleteMany({ organizationId: organization._id });
    console.log('🗑️  Cleared existing customers');

    // Add organizationId to all sample customers
    const customersWithOrg = sampleCustomers.map(customer => ({
      ...customer,
      organizationId: organization._id,
    }));

    // Insert sample customers
    const customers = await Customer.insertMany(customersWithOrg);
    console.log(`✅ Successfully seeded ${customers.length} customers:`);
    
    customers.forEach((customer, index) => {
      console.log(`   ${index + 1}. ${customer.customerCode} - ${customer.companyName}`);
    });

    console.log('\n📊 Summary:');
    console.log(`   Total Customers: ${customers.length}`);
    console.log(`   Active: ${customers.filter(c => c.status === 'Active').length}`);
    console.log(`   Dealers: ${customers.filter(c => c.customerType === 'Dealer').length}`);
    console.log(`   Distributors: ${customers.filter(c => c.customerType === 'Distributor').length}`);
    console.log(`   Retailers: ${customers.filter(c => c.customerType === 'Retailer').length}`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding customers:', error);
    process.exit(1);
  }
};

// Run the seed function
seedCustomers();
