const mongoose = require('mongoose');

const taskSchema = new mongoose.Schema({
  // Task Identification
  taskNumber: {
    type: String,
    unique: true,
    required: true
  },
  title: {
    type: String,
    required: true
  },
  description: {
    type: String
  },
  
  // Task Type & Context
  taskType: {
    type: String,
    enum: [
      'QUOTATION_APPROVAL',
      'DESIGN_CREATION',
      'BOM_GENERATION',
      'MATERIAL_ALLOCATION',
      'PRODUCTION_BEAM_SAW',
      'PRODUCTION_EDGE_BANDING',
      'PRODUCTION_BORING',
      'PRODUCTION_FINISHING',
      'PRODUCTION_STEEL_CUTTING',
      'PRODUCTION_CNC_CUTTING',
      'PRODUCTION_BENDING',
      'PRODUCTION_WELDING',
      'PRODUCTION_PACKAGING',
      'QUALITY_CHECK',
      'INVENTORY_PURCHASE',
      'DISPATCH_PREPARATION',
      'MAINTENANCE_ALERT'
    ],
    required: true
  },
  
  // Linked Entities
  quotation: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Quotation'
  },
  order: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Order'
  },
  productionOrder: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'ProductionOrder'
  },
  workflowStep: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'WorkflowStep'
  },
  inquiry: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Inquiry'
  },
  
  // Workflow Information
  workflowStage: {
    type: String,
    enum: [
      'PRE_PRODUCTION',
      'PRODUCTION',
      'POST_PRODUCTION',
      'QUALITY_ASSURANCE',
      'DISPATCH',
      'SUPPORT'
    ]
  },
  sequence: {
    type: Number,
    default: 0
  },
  
  // Assignment
  assignedTo: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  assignedRole: {
    type: String,
    enum: [
      'POC',
      'SALES_EXECUTIVE',
      'DESIGN_LEAD',
      'DESIGNER',
      'PRODUCTION_MANAGER',
      'CNC_OPERATOR',
      'BEAMSAW_OPERATOR',
      'EDGEBANDING_OPERATOR',
      'BORING_OPERATOR',
      'WELDING_OPERATOR',
      'FINISHING_OPERATOR',
      'QC_INSPECTOR',
      'INVENTORY_MANAGER',
      'LOGISTICS_HEAD',
      'MAINTENANCE_TECHNICIAN'
    ]
  },
  assignedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  assignedAt: {
    type: Date
  },
  
  // Dependencies
  dependsOn: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Task'
  }],
  blockedBy: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Task'
  }],
  
  // Machine Assignment
  requiredMachine: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Machine'
  },
  machineBooked: {
    type: Boolean,
    default: false
  },
  machineBookingSlot: {
    startTime: Date,
    endTime: Date
  },
  
  // Status & Priority
  status: {
    type: String,
    enum: [
      'PENDING',
      'READY',
      'ASSIGNED',
      'IN_PROGRESS',
      'ON_HOLD',
      'BLOCKED',
      'COMPLETED',
      'CANCELLED',
      'FAILED'
    ],
    default: 'PENDING'
  },
  priority: {
    type: String,
    enum: ['LOW', 'MEDIUM', 'HIGH', 'URGENT'],
    default: 'MEDIUM'
  },
  
  // Time Tracking
  estimatedDurationMinutes: {
    type: Number
  },
  actualDurationMinutes: {
    type: Number
  },
  startedAt: {
    type: Date
  },
  completedAt: {
    type: Date
  },
  dueDate: {
    type: Date
  },
  
  // Progress & Results
  progressPercentage: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  },
  completionNotes: {
    type: String
  },
  resultData: {
    type: mongoose.Schema.Types.Mixed
  },
  
  // Quality & Verification
  requiresQC: {
    type: Boolean,
    default: false
  },
  qcStatus: {
    type: String,
    enum: ['NOT_REQUIRED', 'PENDING', 'PASSED', 'FAILED'],
    default: 'NOT_REQUIRED'
  },
  qcCheckedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  qcNotes: {
    type: String
  },
  
  // Notifications
  notificationSent: {
    type: Boolean,
    default: false
  },
  reminderSent: {
    type: Boolean,
    default: false
  },
  escalated: {
    type: Boolean,
    default: false
  },
  escalatedTo: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  
  // Automation Metadata
  autoGenerated: {
    type: Boolean,
    default: false
  },
  generatedBy: {
    type: String,
    enum: ['QUOTATION_APPROVAL', 'PRODUCTION_ORDER', 'RULE_ENGINE', 'MANUAL'],
    default: 'MANUAL'
  },
  automationRuleId: {
    type: String
  },
  
  // Assignment Score (for tracking assignment quality)
  assignmentScore: {
    type: Number
  },
  assignmentReason: {
    type: String
  },
  
  // Status History
  statusHistory: [{
    status: String,
    changedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    changedAt: {
      type: Date,
      default: Date.now
    },
    notes: String
  }],
  
  // Comments & Collaboration
  comments: [{
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    comment: String,
    createdAt: {
      type: Date,
      default: Date.now
    }
  }],
  
  // Tenant Support
  organization: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Organization'
  }
}, {
  timestamps: true
});

// Indexes for performance (taskNumber already has unique index from schema)
taskSchema.index({ assignedTo: 1, status: 1 });
taskSchema.index({ order: 1 });
taskSchema.index({ quotation: 1 });
taskSchema.index({ taskType: 1, status: 1 });
taskSchema.index({ assignedRole: 1, status: 1 });
taskSchema.index({ dueDate: 1 });
taskSchema.index({ organization: 1 });

// Pre-save middleware to generate task number
taskSchema.pre('save', async function(next) {
  if (!this.taskNumber) {
    const year = new Date().getFullYear();
    const count = await mongoose.model('Task').countDocuments({
      taskNumber: new RegExp(`^TSK-${year}-`)
    });
    this.taskNumber = `TSK-${year}-${String(count + 1).padStart(4, '0')}`;
  }
  next();
});

// Methods
taskSchema.methods.markInProgress = function(userId) {
  this.status = 'IN_PROGRESS';
  this.startedAt = new Date();
  this.statusHistory.push({
    status: 'IN_PROGRESS',
    changedBy: userId,
    changedAt: new Date()
  });
};

taskSchema.methods.markCompleted = function(userId, notes) {
  this.status = 'COMPLETED';
  this.completedAt = new Date();
  this.progressPercentage = 100;
  if (notes) {
    this.completionNotes = notes;
  }
  if (this.startedAt) {
    this.actualDurationMinutes = Math.floor((this.completedAt - this.startedAt) / 60000);
  }
  this.statusHistory.push({
    status: 'COMPLETED',
    changedBy: userId,
    changedAt: new Date(),
    notes
  });
};

taskSchema.methods.assignToUser = function(userId, assignedBy, reason) {
  this.assignedTo = userId;
  this.assignedBy = assignedBy;
  this.assignedAt = new Date();
  this.assignmentReason = reason;
  this.status = 'ASSIGNED';
  this.statusHistory.push({
    status: 'ASSIGNED',
    changedBy: assignedBy,
    changedAt: new Date(),
    notes: `Assigned to user. Reason: ${reason}`
  });
};

taskSchema.methods.canStart = async function() {
  if (this.dependsOn.length === 0) return true;
  
  const Task = mongoose.model('Task');
  const dependencies = await Task.find({
    _id: { $in: this.dependsOn }
  });
  
  return dependencies.every(dep => dep.status === 'COMPLETED');
};

taskSchema.methods.isOverdue = function() {
  if (!this.dueDate) return false;
  return new Date() > this.dueDate && this.status !== 'COMPLETED';
};

// Static methods
taskSchema.statics.getTasksByOrder = function(orderId) {
  return this.find({ order: orderId }).sort({ sequence: 1 }).populate('assignedTo requiredMachine');
};

taskSchema.statics.getTasksByUser = function(userId, status) {
  const query = { assignedTo: userId };
  if (status) query.status = status;
  return this.find(query).sort({ priority: -1, dueDate: 1 }).populate('order quotation requiredMachine');
};

taskSchema.statics.getTasksByRole = function(role, status) {
  const query = { assignedRole: role };
  if (status) query.status = status;
  return this.find(query).sort({ priority: -1, dueDate: 1 }).populate('order quotation');
};

taskSchema.statics.getPendingTasksCount = function(userId) {
  return this.countDocuments({
    assignedTo: userId,
    status: { $in: ['PENDING', 'READY', 'ASSIGNED', 'IN_PROGRESS'] }
  });
};

taskSchema.statics.getOverdueTasks = function(userId) {
  return this.find({
    assignedTo: userId,
    status: { $ne: 'COMPLETED' },
    dueDate: { $lt: new Date() }
  }).sort({ dueDate: 1 });
};

module.exports = mongoose.model('Task', taskSchema);
